name: Download and Upload Zip File Directly

on:
  workflow_dispatch: # 手動でワークフローを実行できるようにします

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download zip file with retry
      # curlコマンドで指定されたURLからZIPファイルをダウンロードします。
      # --retryと--retry-delayオプションでダウンロードの信頼性を高めています。
      run: |
        curl -L -o hujikopro_-_chipbreak_is_dead.zip --retry 3 --retry-delay 5 https://vol4records.com/music/%5BVL4-043%5Dhujikopro_-_chipbreak_is_dead.zip

    - name: Configure Git
      # Gitコミットのためにユーザー名とメールアドレスを設定します。
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Add and commit changes
      # ダウンロードしたZIPファイルをGitに追加し、コミットしてプッシュします。
      # GITHUB_TOKENは、リポジトリへの書き込み権限を持つGitHub Actionsのデフォルトのトークンです。
      run: |
        git add hujikopro_-_chipbreak_is_dead.zip
        git commit -m "Upload hujikopro_-_chipbreak_is_dead.zip"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
